# dynamic.yaml

http:
  middlewares:
    traefikAuth:
      basicAuth:
        users:
          - "admin:$6$OrZO7Wb3SVa4OfBT$Csqb2zcbVPYhMLaud5vRIcPKwxmr18iVK/o84GZsJ4/P.6nLWBOkzJfJpXW.f5yM14zHDBJJW5/uAIf9KV0IP/"

  services:
    portainer-service:
      loadBalancer:
        servers:
          - url: "https://192.168.10.53:9443"  # Change container name and port accordingly

