global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: INFO

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
       entryPoint:
         to: "websecure"
         scheme: "https"
  websecure:
    address: :443

certificatesResolvers:
  cloudflare:
    acme:
      email: lily.sabath@nachlesen.com
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      keyType: EC256
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "9.9.9.9:53"

providers:
  docker:
    exposedByDefault: false
    watch: true
    swarmMode: false
  file:
    filename: "/etc/traefik/dynamic.yml"
    watch: true

tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_RSA_WITH_AES_256_GCM_SHA384"
