traefik:
# The official v2 Traefik docker image
  image: traefik:v2.10
  #container-name: traefik
  ports:
    # The HTTP port
    - "80:80"
    - "443:443"
    # The Web UI (enabled by --api.insecure=true)
    - "8080:8080"
  volumes:
    - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      # - /etc/letsencrypt/live/witchessabath:/etc/traefik/certs
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./config/certs/:/etc/traefik/certs/
    - ./config/conf/:/etc/traefik/conf/
  networks:
    - traefik
  restart: unless-stopped
