services:
  traefik:
    container_name: traefik
    image: traefik:v2.10
    ports:
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - ./conf/traefik.yml:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs/:/etc/traefik/certs/
    environment:
      - "CLOUDFLARE_EMAIL=xxx"
      - "CLOUDFLARE_API_KEY=xxx"
    restart: unless-stopped
