global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: ERROR
  format: common
  filePath: /var/log/traefik/access.log

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
       entryPoint:
         to: websecure
         scheme: https
  websecure:
    address: :443

certificatesResolvers:
  staging:
    acme:
      email: lily.sabath@nachlesen.com
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entrypoint: web

  production:
    acme:
      email: lily.sabath@nachlesen.com
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web
      tlsChallenge: {}
      domains:
        - main: witchessabath.com
          sans:
            - '*.witchessabath.com'

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik/conf/
    watch: true
